# Generated by Django 3.2.8 on 2021-10-22 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_swimming'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimming',
            name='penguin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.penguin'),
            preserve_default=False,
        ),
    ]
