# Generated by Django 3.2.8 on 2021-10-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_swimming_penguin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swimming',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='swimming',
            name='date',
            field=models.DateField(verbose_name='swimming date'),
        ),
    ]
