# Generated by Django 3.2.8 on 2021-10-26 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20211025_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('penguin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.penguin')),
            ],
        ),
    ]
